name: test
run-name: ${{ github.actor }} runs test
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run linter
        run: poetry run pflake8 ./src/
      - name: Run type check
        run: poetry run mypy ./src/

